Add linkchecker workflow
Signed-off-by: Luke Mondy <luke.mondy@data61.csiro.au>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,10 +11,20 @@ jobs:
   snapshot:
     name: "Static snapshot"
     runs-on: 'ubuntu-latest'
+    outputs:
+      linkchecker_failed: ${{ steps.linkchecker_status.outputs.linkchecker_failed }}
     steps:
       - uses: actions/checkout@v2
       - uses: ./.github/actions/gen_static_website
         id: 'gen_static_website'
+      - name: Check status of linkchecker
+        id: linkchecker_status
+        run: |
+          if [ -e ".linkchecker_failed" ]; then
+            echo "::set-output name=linkchecker_failed::true"
+          else
+            echo "::set-output name=linkchecker_failed::false" 
+          fi
       - name: show files
         run: |
           ls -lan
@@ -46,7 +56,26 @@ jobs:
         with:
           msg: "Review your changes [here](https://htmlpreview.github.io/?https://github.com/LukeMondy/website_pr_hosting/blob/${{ github.actor }}/localhost/index.html)"
           check_for_duplicate_msg: false
-        
+  linkchecker:
+    name: "Link checker"
+    runs-on: 'ubuntu-latest'
+    needs: snapshot
+    steps:
+      - name: Leave comment with link to linkchecker results
+        if:
+          needs.snapshot.outputs.linkchecker_failed
+        uses: unsplash/comment-on-pr@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          msg: "The link checker found some issues! Review them [here](https://htmlpreview.github.io/?https://github.com/LukeMondy/website_pr_hosting/blob/${{ github.actor }}/localhost/linkchecker.html)"
+          check_for_duplicate_msg: false
+      - name: show linkchecker status
+        run: |
+          if ${{ needs.snapshot.outputs.linkchecker_failed }}; then
+            exit 1
+          fi
+          exit 0
         
         
         
