Implement HTML5 validation check.
Merge other results into a single comment.

Signed-off-by: Luke Mondy <luke.mondy@data61.csiro.au>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,10 +13,13 @@ jobs:
     runs-on: 'ubuntu-latest'
     outputs:
       linkchecker_failed: ${{ steps.linkchecker_status.outputs.linkchecker_failed }}
+      validator_failed:   ${{ steps.validator_status.outputs.validator_failed }}
     steps:
       - uses: actions/checkout@v2
+
       - uses: ./.github/actions/gen_static_website
         id: 'gen_static_website'
+
       - name: Check status of linkchecker
         id: linkchecker_status
         run: |
@@ -25,18 +28,49 @@ jobs:
           else
             echo "::set-output name=linkchecker_failed::false" 
           fi
-      - name: show files
+
+      - name: Fix up HTML5 validator log paths
+        run: sed -i 's|/github/workspace/snapped_site/localhost||g' snapped_site/localhost/linkchecker.html
+
+      - name: HTML5 Validator
+        id: validate
+        # TODO: revert back to Cyb3r-Jak3/html5validator-action@master
+        # once my PR is merged
+        uses: LukeMondy/html5validator-action@master
+        with:
+          root: snapped_site/localhost
+          format: text
+        continue-on-error: true
+
+      - name: Check status of HTML5 validator
+        id: validator_status
         run: |
-          ls -lan
+          if [ "${{ steps.validate.outputs.result }}" -eq "0" ]; then
+            echo "::set-output name=validator_failed::false"
+          else
+            echo "::set-output name=validator_failed::true" 
+          fi
+
+      - name: Fix up HTML5 validator log paths
+        run: |
+          output="snapped_site/localhost/validator.log"
+          # Make some very dodgey HTML, so we can get nicer output
+          echo "<html><body><p>" > "$output"
+          sed 's|/github/workspace/snapped_site/localhost||g' log.log \
+            | sed "s|'Error:|</p><p>Error:|g" \
+            | sed "s|', '|<br />|g" \
+            >> "$output"
+          echo "</p></body></html>" >> "$output"
+
       - name: Commit files
         run: |
-          # TODO: snapped_site either needs to be a variable everywhere, or not at all.
           cd snapped_site
           git init .
           git add *
           git config --local user.email "auto@sel4.systems"
           git config --local user.name "seL4 GitHubAction"
           git commit -m "Add changes" -a
+
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
@@ -49,33 +83,63 @@ jobs:
           force: true
           repository: LukeMondy/website_pr_hosting
           directory: snapped_site
-      - name: Leave comment with URL
-        uses: unsplash/comment-on-pr@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          msg: "Review your changes [here](https://htmlpreview.github.io/?https://github.com/LukeMondy/website_pr_hosting/blob/${{ github.actor }}/localhost/index.html)"
-          check_for_duplicate_msg: false
+
   linkchecker:
     name: "Link checker"
     runs-on: 'ubuntu-latest'
     needs: snapshot
+    continue-on-error: true
     steps:
-      - name: Leave comment with link to linkchecker results
-        if:
-          needs.snapshot.outputs.linkchecker_failed
-        uses: unsplash/comment-on-pr@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          msg: "The link checker found some issues! Review them [here](https://htmlpreview.github.io/?https://github.com/LukeMondy/website_pr_hosting/blob/${{ github.actor }}/localhost/linkchecker.html)"
-          check_for_duplicate_msg: false
       - name: show linkchecker status
         run: |
           if ${{ needs.snapshot.outputs.linkchecker_failed }}; then
             exit 1
           fi
           exit 0
+
+  htmlvalidator:
+    name: "HTML5 Validator"
+    runs-on: 'ubuntu-latest'
+    needs: snapshot
+    continue-on-error: true
+    steps:
+      - name: show validator status
+        run: |
+          if ${{ needs.snapshot.outputs.validator_failed }}; then
+            exit 1
+          fi
+          exit 0
         
-        
+  commenter:
+    name: "Report results as comment"
+    runs-on: 'ubuntu-latest'
+    needs: [snapshot , linkchecker, htmlvalidator]
+    steps:
+      - name: Build message
+        run: |
+          echo "Preview your changes [here](https://htmlpreview.github.io/?https://github.com/LukeMondy/website_pr_hosting/blob/${{ github.actor }}/localhost/index.html)" > msg.txt
+          if ${{ needs.snapshot.outputs.linkchecker_failed }}; then
+            echo "" >> msg.txt
+            echo "The link checker found some issues! Review them [here](https://htmlpreview.github.io/?https://github.com/LukeMondy/website_pr_hosting/blob/${{ github.actor }}/localhost/linkchecker.html)" >> msg.txt
+          fi
+          if ${{ needs.snapshot.outputs.validator_failed }}; then
+            echo "" >> msg.txt
+            echo "The HTML5 validator found some issues! Review them [here](https://htmlpreview.github.io/?https://github.com/LukeMondy/website_pr_hosting/blob/${{ github.actor }}/localhost/validator.log)" >> msg.txt
+          fi
+          export MSG=$(cat msg.txt)
+          # The follow lines are to preserve newlines
+          MSG="${MSG//'%'/'%25'}"
+          MSG="${MSG//$'\n'/'%0A'}"
+          MSG="${MSG//$'\r'/'%0D'}"
+          echo "::set-env name=MSG::$MSG"
+      - name: Print message
+        run: |
+          echo "$MSG"
+      - name: Leave comment with link to site, and results of checks
+        uses: unsplash/comment-on-pr@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          msg: "${{ env.MSG }}"
+          check_for_duplicate_msg: false
         
